global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'observability_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:4000']  # Assumes Phoenix app runs on port 4000
    scrape_interval: 5s